name: 'install-pinned/twine'
description: 'Securely install the latest twine release from PyPI'
branding:
  icon: 'lock'
  color: 'green'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        pyver=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
        python3 -m pip install -r $GITHUB_ACTION_PATH/pins/requirements-$pyver-$RUNNER_OS.txt
